const items = [
    {
        ietmCode: "1",
        name: "ADC",
        purchasePrice: 1,
        salePrice: 3,
        minSalePrice: 2,
        mrp: 10,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "2",
        name: "ASD",
        purchasePrice: 123,
        salePrice: 200,
        minSalePrice: 150,
        mrp: 1034,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "3",
        name: "VDVG",
        purchasePrice: 231,
        salePrice: 400,
        minSalePrice: 300,
        mrp: 1220,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "4",
        name: "DVDFVB",
        purchasePrice: 421,
        salePrice: 600,
        minSalePrice: 500,
        mrp: 1230,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "5",
        name: "SDV",
        purchasePrice: 111,
        salePrice: 222,
        minSalePrice: 150,
        mrp: 13210,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "SDFKJDKLJGVBJ KJSZDBHFJKVHBJDS",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "6",
        name: "DSVCX",
        purchasePrice: 421,
        salePrice: 523,
        minSalePrice: 450,
        mrp: 1320,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "7",
        name: "CXZCVD",
        purchasePrice: 1,
        salePrice: 3,
        minSalePrice: 2,
        mrp: 1320,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: false,
        description: "",
        imageUrl: "https://smania.si/v1/interaktiven-zepni-robotek-minibot/product-img/slide-2.jpg"
    },
    {
        ietmCode: "400",
        name: "robotek 5c",
        purchasePrice: 165,
        salePrice: 250,
        minSalePrice: 210,
        mrp: 1034,
        unit: "pcs",
        stock: 10,
        isSaleDiscount: true,
        description: "trst senerio",
        imageUrl: "https://1.bp.blogspot.com/-Nu-zFJ2OBUo/YEnrDPwD3kI/AAAAAAAAAPw/GGgP_3V0oQUb3tDPSmUMJ9m8ByKVGkHnACLcBGAsYHQ/s2000/20210311_143227.jpg"
    },
    {
        ietmCode: "300",
        name: "Boat Neckband",
        purchasePrice: 1165,
        salePrice: 2150,
        minSalePrice: 1210,
        mrp: 4999,
        unit: "pcs",
        stock: 6,
        isSaleDiscount: true,
        description: "trst senerio",
        imageUrl: "https://1.bp.blogspot.com/-wdxWq942v6k/YNL09iCQ1OI/AAAAAAAABjE/CjWZ_7gxmeUhvc8czZqO5HqV64bmwb_egCLcBGAsYHQ/s16000/61yzM3VYQqL._SL1500_.jpg"
    }
];

export default items;